# Generated by Django 5.1.4 on 2024-12-26 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safety', '0002_achievement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('contact', models.CharField(max_length=100)),
                ('imageFile', models.ImageField(upload_to='products/')),
            ],
        ),
        migrations.DeleteModel(
            name='Achievement',
        ),
    ]
